version: '3.8'

services:
  # WordPress service
  wordpress:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80" 
    depends_on:
      - db
    volumes:
      - wordpress_data:/var/www/html

  # Database service (e.g., MySQL)
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password
      MYSQL_DATABASE: your_db_name
      MYSQL_USER: your_db_user
      MYSQL_PASSWORD: your_db_password
    volumes:
      - db_data:/var/lib/mysql

volumes:
  wordpress_data:
  db_data:

